src/main/java/org/jboss/aesh/console/AeshConsoleCallback.java

Line 184 in commit https://github.com/stalep/wildfly-core/commit/df5dcfe368aab287481c206f6573dbcbc244fad2 is throwing null-pointer errors when the CLI starts up. Clean build, but the CLI startup fails. Traced it back to the process not existing when the first read gets called. Not sure if you want it handled here or elsewhere.

Throwing null-pointer

---

src/main/java/org/jboss/aesh/io/PathResolver.java
src/test/java/org/jboss/aesh/io/PathResolverTest.java

For Windows platform the root path do not start with "/" bur more like C: 
Hope that help.
Regards,
Jérémie.

[AESH-298] manage root path with driver name in PathResolver (cloverxell issue #87)

---

src/main/java/org/jboss/aesh/console/settings/DefaultAeshContext.java
src/main/java/org/jboss/aesh/console/settings/SettingsImpl.java

I needed my own AeshContext for Artificer and used AeshContextImpl to provide the base methods.  But, it's easier to extend with this PR.  Also re-named it DefaultAeshContext.  Feel free to take it or leave it -- not sure if others are extending it as-is and whether or not this would be breaking.

create DefaultAeshContext and make it easy to extend

---

src/main/java/org/jboss/aesh/console/AeshInputProcessor.java

Necessary to put the next prompt after a ctrl-c exit on a clean line.

Adding newline before interrupt

---

src/main/java/org/jboss/aesh/console/Console.java

Simplest solution for nesting commands on the low-level API.
It leaves it up to whoever is using AESH to create their own callbackhandler that keeps track of the active process PID, if there is an active process, to pass into the methods.
I figure if they want AESH to take care of the PID handling they should be using the high-level API.

Allow for nested processes via low-level API

---

src/test/java/org/jboss/aesh/console/aesh/AeshNestedCommandTest.java
src/test/java/org/jboss/aesh/console/aesh/ConsoleNestedCommandTest.java

Tests using putProcessInBackground() and putProcessInForeground() from the CommandInvocation and Console levels.
In the Console level the test has to track the PID used to push/pull the active process. The high-level CommandInvocation API handles that on it's own.

Command nesting tests in both high-level and low-level APIs

---

src/main/java/org/jboss/aesh/console/AeshCompletionHandler.java
src/main/java/org/jboss/aesh/console/AeshInputProcessor.java
src/main/java/org/jboss/aesh/console/CompletionHandler.java
src/main/java/org/jboss/aesh/console/Console.java
src/main/java/org/jboss/aesh/console/InputProcessor.java
src/main/java/org/jboss/aesh/console/settings/Settings.java
src/main/java/org/jboss/aesh/console/settings/SettingsImpl.java
src/test/java/org/jboss/aesh/console/ConfigTest.java
src/test/java/org/jboss/aesh/console/completion/CompletionConsoleTest.java

Necessary in order to disable completion on nested commands. If, for example, a nested command is requesting a username/password, completion needs to be off. Tried to design it like enabling/disabling history worked. Keeping the variable and functionality within the the CompletionHandler instead of the Console or InputProcessor. 
I think I need to give more thought to nested commands in general. Ideally they would be almost brand new consoles, with their own settings and handlers. I'm not sure how complicated that would be though. Could require a lot of work.

Runtime enable/disable of completion capabilities

---

src/main/java/org/jboss/aesh/console/Buffer.java

If the length() method in line 109 is going to return 1 when null masking is enabled, then the cursor location has to be 1 when it's enabled. Otherwise the cursor will move forward 1 column when backspace is used.

Fixing cursor movement when using null character masking and hitting backspace

---

src/main/java/org/jboss/aesh/console/Buffer.java

Changing previous fix for cursor movement during 0 masking issue. Previous solution introduced ArrayIndexOutOfBounds exceptions in certain edge cases.
The existing tests in AeshInputProcessorTest don't cover zero-masking correctly, because they get the buffer 'line', which always returns nothing, but doesn't necessarily reflect the actual console output. However, I've been messing with input and output streams all day and can't get a test for it to work correctly.

Fixing Cursor movement while using Zero-Masking

---

src/main/java/org/jboss/aesh/util/LoggerUtil.java

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1237035

[AESH-323] Files are still created in /tmp/ even if logging is disabled.

---

src/main/java/org/jboss/aesh/console/Console.java

Odd edge-case. In some CLI scenarios the console can be created, but then closed without being started. The terminal still needs to reset.
I'm not sure if the other stream closing, lines 436-438, might need this change as well. I only encountered the terminal problem specifically.

Terminal needs to reset on close even if the console has not been started and running=false

---

src/main/java/org/jboss/aesh/console/Console.java

Aesh should never attempt to close streams that were not created by Aesh. 
Attempting to close it while reading the stream provokes a deadlock

Avoid closing stderr and stdout

---

src/main/java/org/jboss/aesh/console/alias/AliasManager.java
src/test/java/org/jboss/aesh/console/alias/AliasManagerTest.java

When writing its persistent file, the AliasManager drop the existing one and replace it with an empty directory. The bug can be seen with the AeshExample or with WildFly 10.CR4.
With the fix, it creates the parent directory when needed and the only creates the file.

Fix creation of .aesh_alias file

---

src/main/java/org/jboss/aesh/cl/internal/ProcessedCommand.java
src/main/java/org/jboss/aesh/cl/internal/ProcessedOption.java
src/main/java/org/jboss/aesh/cl/parser/AeshCommandLineParser.java
src/main/java/org/jboss/aesh/console/command/map/MapCommand.java
src/main/java/org/jboss/aesh/console/command/map/MapCommandPopulator.java
src/main/java/org/jboss/aesh/console/command/map/MapProcessedCommandBuilder.java

The idea is to introduce a subinterface of Command<T>, the MapCommand<T>, that stores the injected options into a Map. This allows user to define Command dynamically, outside of any need for a Class to describe the Command/Options.
In addition this change allows to compute options (Thanks to the ProcessedOptionprovider interface) and sub commands on the fly.
Usage example:
// Create the Command that will receive command execution
MapCommand<CliCommandInvocation> com = new MapCommand<>() {
public CommandResult execute(CliCommandInvocation commandInvocation) {
String value = getValue("option1");   
....
};
// Create a ProcessedCommand that describes the Command. Can be used with a set of known options
// or with a ProcessedOptionProvider
ProcessedCommand command = new …

Allow for Command with dynamic options and dynamic child commands

---

src/main/java/AeshExample.java
src/main/java/org/jboss/aesh/cl/GroupCommandDefinition.java
src/main/java/org/jboss/aesh/cl/activation/CommandActivator.java
src/main/java/org/jboss/aesh/cl/activation/NullCommandActivator.java
src/main/java/org/jboss/aesh/cl/internal/ProcessedCommand.java
src/main/java/org/jboss/aesh/cl/internal/ProcessedCommandBuilder.java
src/main/java/org/jboss/aesh/cl/parser/ParserGenerator.java
src/main/java/org/jboss/aesh/console/AeshConsoleBuilder.java
src/main/java/org/jboss/aesh/console/AeshConsoleImpl.java
src/main/java/org/jboss/aesh/console/AeshInvocationProviders.java
src/main/java/org/jboss/aesh/console/command/activator/AeshCommandActivatorProvider.java
src/main/java/org/jboss/aesh/console/command/activator/CommandActivatorProvider.java
src/main/java/org/jboss/aesh/console/command/map/MapProcessedCommandBuilder.java
src/main/java/org/jboss/aesh/console/command/registry/MutableCommandRegistry.java
src/test/java/org/jboss/aesh/cl/CommandLinePopulatorTest.java
src/test/java/org/jboss/aesh/console/aesh/AeshCommandCompletionTest.java

Introduce a CommandActivator to hide command from completion when appropriate.

Fix for AESH-353

---

src/main/java/org/jboss/aesh/console/alias/AliasCompletion.java

see https://issues.jboss.org/browse/AESH-390

[AESH-390] Fix issue that Alias --help completion is always added if word is empty.

---

src/main/java/AeshExample.java
src/main/java/org/jboss/aesh/cl/activation/CommandActivator.java
src/main/java/org/jboss/aesh/cl/activation/NullCommandActivator.java
src/main/java/org/jboss/aesh/cl/parser/ParserGenerator.java
src/main/java/org/jboss/aesh/console/command/GroupCommand.java
src/main/java/org/jboss/aesh/console/command/registry/MutableCommandRegistry.java
src/test/java/org/jboss/aesh/console/aesh/AeshCommandCompletionTest.java

Take into account commands that implements GroupCommand. Make CommandActivator to take ProcessedCommand as parameter, it allows to share state between Command and Activator (same pattern as OptionActivator).

Fix for AESH-388

---

src/main/java/org/jboss/aesh/console/Console.java

In order to have running to reflect the fact that the console is fully closed.

Fix for AESH-429. Change running flag at the end of close

---

build.gradle

Need the nexus repo to build if you don't have aesh-readline in your local repo.

added nexus repo

---

src/main/java/org/aesh/command/impl/Executions.java
src/main/java/org/aesh/command/impl/operator/AppendOutputRedirectionOperator.java
src/main/java/org/aesh/command/impl/operator/EndOperator.java
src/main/java/org/aesh/command/impl/operator/ExecutableOperator.java
src/main/java/org/aesh/command/impl/operator/FileOutputDelegate.java
src/main/java/org/aesh/command/impl/operator/OutputDelegate.java
src/main/java/org/aesh/command/impl/operator/OutputRedirectionOperator.java
src/main/java/org/aesh/command/impl/operator/PipeOperator.java
src/main/java/org/aesh/command/invocation/CommandInvocationConfiguration.java
src/main/java/org/aesh/command/operator/OperatorType.java

I am treating the Pipe operator as a dual operator. It is similar to the OutputRedirection in the sense that it should trap the output of the previous command, but in addition this operator is executable, it means that the previous command as to be executed when encountering the '|', no need for ';' operator.
So the pipe operator will configure the CommandInvocation with an OutputDelegate that keeps the output from the previous command in memory array.
Once executed, the output from the previous command is available from the CommandInvocation, making next command to be able to use it.
The mesh-extensions grep command has been re-implemented on top of it and works as expected.

Intial support for Pipe operator and injection

---

src/main/java/org/aesh/command/impl/Executions.java
src/main/java/org/aesh/parser/LineParser.java
src/main/java/org/aesh/parser/ParsedLineIterator.java
src/test/java/org/aesh/parser/LineParserTest.java

- Lazy creation of the CommandInvocation. 
Imagine 2 commands on the same line, first one change in some way the execution context. When the second command is executed, it must have its CommandInvocation in sync with the changes done by the previous command.
The CommandInvocation is now built when retrieved (just prior to execution).
- Expose the original line from the parser iterator.

Lazy CommandInvocation creation. Expose original line from cursor

---

src/main/java/org/aesh/command/AeshCommandRuntimeBuilder.java
src/main/java/org/aesh/command/CommandResolver.java
src/main/java/org/aesh/command/impl/AeshCommandResolver.java
src/main/java/org/aesh/command/impl/AeshCommandRuntime.java
src/main/java/org/aesh/console/settings/SettingsBuilder.java
src/test/java/org/aesh/console/aesh/AeshCommandEndOperatorTest.java
src/test/java/org/aesh/console/aesh/AeshCommandPipelineTest.java

Make settingsBuilder aware of operators.
Updated tests to unignore them. PipeTest has been reversed. The command after the pipe not before the pipe checks for available data.

Operator unit test. Makes SettingsBuilder operator aware

---

src/main/java/org/jboss/aesh/parser/Parser.java
src/test/java/org/jboss/aesh/parser/ParserTest.java

https://issues.jboss.org/browse/AESH-435
In case that list element is longer than terminal width, Parser.formatDisplayList() set maxLength to longest element length. This will make all other short elements hold unnecessary lines. This makes an unfriendly output format as attached in issue.
This is for 0.66.+ I don't see same Parser.java in master branch.

[AESH-435] restrict maxLength to termial width.

---

src/main/java/org/jboss/aesh/terminal/POSIXTerminal.java
src/main/java/org/jboss/aesh/terminal/Terminal.java
src/main/java/org/jboss/aesh/terminal/TestTerminal.java
src/main/java/org/jboss/aesh/terminal/WindowsTerminal.java

This helps in CLI non interactive mode to get values of terminal where it launches non interactive mode, without a console instance.
https://issues.jboss.org/browse/AESH-435
related change in CLI is https://github.com/soul2zimate/wildfly-core/commits/WFCORE-2812-non-interactive

[AESH-435] expose terminal height and width.

---

pom.xml

Needed due to Parser API change.

Fix readline dependency

---

src/main/java/org/aesh/command/impl/Executions.java
src/main/java/org/aesh/command/impl/operator/PipeOperator.java
src/main/java/org/aesh/command/invocation/CommandInvocationConfiguration.java
src/main/java/org/aesh/readline/ProcessManager.java
src/test/java/org/aesh/console/redirect/ConsoleRedirectionTest.java

Added support (impl and test) for:
- cmd1 < toto > titi
- cmd1 | cmd2 > titi
- cmd1 < toto | cmd2
- cmd1 < toto | cmd2 > titi
Found a bug in ProcessManager, seems that the wrong execution was called at some point.

More advanced support for operator combinations

---

src/main/java/Example.java
src/main/java/org/aesh/command/impl/Executions.java
src/main/java/org/aesh/command/impl/invocation/AeshCommandInvocation.java
src/main/java/org/aesh/command/impl/invocation/DefaultCommandInvocation.java
src/main/java/org/aesh/command/impl/shell/ShellOutputDelegate.java
src/main/java/org/aesh/command/invocation/CommandInvocation.java
src/main/java/org/aesh/command/shell/Shell.java
src/main/java/org/aesh/readline/ReadlineConsole.java
src/main/java/org/aesh/readline/ShellImpl.java
src/test/java/org/aesh/command/invocation/AeshCommandInvocationServiceTest.java

Wrongly formatted command such as: cmd || ==> NPE
Shell and CommandInvocation exposes 2 new methods to ask for paging. Added a long-output command to Example (can take a --prompt to observe that paged output is displayed prior to prompt).
Manually tested that input redirection bypass the paging and print it all.

NPE in Executions

---

src/main/java/org/aesh/command/impl/internal/ProcessedCommand.java

We need to keep the longest match to avoid option selection mismatch

Fix for AESH-453, issues for options having a common part name

---

src/main/java/org/aesh/command/impl/Executions.java
src/main/java/org/aesh/parser/LineParser.java
src/main/java/org/aesh/parser/ParsedLine.java
src/test/java/org/aesh/parser/LineParserTest.java
src/test/java/org/aesh/parser/ParsedLineTest.java

AESH: https://issues.jboss.org/browse/AESH-456
WFCORE: https://issues.jboss.org/browse/WFCORE-3554

[AESH-456] Append the content to the file with name tmp|file results to 'tmp\|file' being created

---

aesh/src/main/java/org/aesh/command/impl/internal/ProcessedCommand.java
aesh/src/main/java/org/aesh/command/impl/parser/AeshCommandLineParser.java
aesh/src/main/java/org/aesh/command/map/MapCommand.java
aesh/src/main/java/org/aesh/command/map/MapCommandPopulator.java
aesh/src/main/java/org/aesh/command/map/MapProcessedCommandBuilder.java

The retrieval of dynamic options can be costly and needed only at completion time.
This change refactors ProcessedCommand in order for MapProcessedCommand to minimize the number of time options are retrieved.

Minimize the number of time dynamic options are recomputed.

---

aesh/src/main/java/org/aesh/readline/ReadlineConsole.java

When using the "exit" command from aesh extension, 2 new lines are printed. The expected one (to execute the command), and a not expected one printed by the console when existing.
In order to still have a new line when Ctrl-D is typed, aesh-readline Ctrl-D action must print a new line prior to close the connection. That is:https://github.com/aeshell/aesh-readline/pull/34

No need for new line when exiting

---

aesh/src/main/java/org/aesh/command/impl/AeshCommandRuntime.java
aesh/src/main/java/org/aesh/readline/ReadlineConsole.java

- Removed call to doLog from ReadlineConsole, that is handled in SettingsBuilder if logging is set to true.
- Added a fine trace for each executed command.

Fix for AESH-488, ReadlineConsole doesn't take into account logging flag

---

aesh/src/main/java/org/aesh/command/impl/parser/AeshOptionParser.java
aesh/src/test/java/org/aesh/command/parser/CommandLineParserTest.java

Allow `@Option(shortName = 'e') String e` be used as `test -ebar`.

Allow short-name option without =

---

aesh/src/main/java/org/aesh/command/impl/internal/ProcessedCommand.java
aesh/src/test/java/org/aesh/command/builder/CommandLineFormatterTest.java

The old behaviour of printing the help text is as follows:
```
Usage: command description
Options:
--help
```
This is confusing because in the 'Usage' line, we're expecting the
cli-options to appear, and one might think that 'description' is a CLI
sub-command instead of the description itself (especially if the
description is short).
Instead, this commit puts the description in a new line to avoid this
confusion.
```
Usage: command
description
Options:
--help
```

Put description in its own line for cli printHelp

---

aesh/src/main/java/org/aesh/command/CommandRuntime.java

In `CommandRuntime`, once we get the desired `CommandContainer` object
for method `commandInfo`, we should pass the full 'line' String to
`commandContainer.printHelp`.
If the CommandContainer is a group command, the `printHelp` method
accepts multiple tokens in the parameter to help it find the correct
child parser (or sub-command/sub-groupcommand) to invoke the `printHelp`
method.
for e.g the 'line' string can be: 'main-group sub-group'
With the change in that commit, the CommandContainer for 'main-group'
will figure out that we want to find the child parser of 'sub-group' to
print its help text.

printHelp in CommandRuntime should consider full param string

---

aesh/src/main/java/org/aesh/command/impl/parser/AeshCommandLineParser.java
aesh/src/main/java/org/aesh/command/impl/parser/CommandLineParser.java
aesh/src/test/java/org/aesh/command/builder/CommandLineFormatterTest.java
pom.xml

This commit aligns the command names and the command description, and adds a dash of color to the command name (can be disabled by calling updateAnsiMode(false))

Align command name and command description and add color

---

aesh/src/main/java/org/aesh/command/container/DefaultCommandContainer.java

In case the user is invoking a wrong command and/or sub-command, a NPE
is thrown. This PR attempts to throw a more meaningful exception
(CommandLineparserException) and the reason for the stacktrace.

Warn user of wrong command
