aeshell/aesh

build.gradle
src/main/java/AeshGraphicsExample.java
src/main/java/org/jboss/aesh/graphics/AeshGraphics.java
src/main/java/org/jboss/aesh/graphics/Graphics.java

* added {@inheritDoc}
* clear and cleanup - clear distinction ( clear - clearnAndShowCursor )
* gradle javadoc task

javadoc gradle task, graphics api name changed, and others

---

build.gradle

install task now run checkstyle and unit tests.

---

src/main/java/org/jboss/aesh/cl/completer/CompleterData.java
src/main/java/org/jboss/aesh/console/command/completer/CompleterInvocation.java

Try not to get overwhelmed with this incredibly complex contribution ;)
Where possible, allow Collections to be given as CompleterInvocation args.  Artificer builds up Sets for a few commands, and I'm sure others may bump up against that as well.

allow any Collection in CompleterInvocation methods

---

src/main/java/AeshExample.java
src/main/java/org/jboss/aesh/cl/parser/AeshCommandLineParser.java
src/main/java/org/jboss/aesh/console/AeshConsoleImpl.java
src/main/java/org/jboss/aesh/console/command/container/CommandContainer.java
src/main/java/org/jboss/aesh/console/command/container/DefaultCommandContainer.java
src/main/java/org/jboss/aesh/console/command/registry/MutableCommandRegistry.java
src/test/java/org/jboss/aesh/cl/CommandLineFormatterTest.java

added support for help info for group commands

[AESH-303]

---

src/main/java/org/jboss/aesh/io/FileResource.java
src/main/java/org/jboss/aesh/io/Resource.java

used by touch command from extensions.

new methods to get and set last accessed time from resource

---

src/main/java/org/jboss/aesh/edit/mapper/KeyMapper.java

https://issues.jboss.org/browse/AESH-316

[AESH-316] - print warning instead of exception on unsupported C-

---

src/main/java/org/jboss/aesh/console/reader/ConsoleInputSession.java

Adding a '-1' char in the queue to tell to the "Aesh Read Loop" thread it is the end ...

[AESH-317]"Aesh Read Loop" thread leaks

---

src/main/java/org/jboss/aesh/console/Console.java
src/main/java/org/jboss/aesh/console/reader/AeshInputStream.java
src/main/java/org/jboss/aesh/console/reader/ConsoleInputSession.java

Force shutdown of the Executor Service.

[AESH-318] "Aesh Executor Service" thread leaks

---

src/main/java/org/jboss/aesh/history/InMemoryHistory.java
src/test/java/org/jboss/aesh/history/HistoryTest.java

https://issues.jboss.org/browse/WFCORE-791

Changing history behavior to allow duplicates, but not repeated commands

---

src/main/java/org/jboss/aesh/terminal/TestTerminal.java

https://issues.jboss.org/browse/AESH-329

[AESH-329] don't close System.in

---

src/main/java/org/jboss/aesh/console/Console.java
src/main/java/org/jboss/aesh/console/reader/ConsoleInputSession.java
src/main/java/org/jboss/aesh/terminal/POSIXTerminal.java
src/main/java/org/jboss/aesh/terminal/Terminal.java
src/main/java/org/jboss/aesh/terminal/TestTerminal.java
src/main/java/org/jboss/aesh/terminal/WindowsTerminal.java

Allows a program to 'use' AESH and more accurately imitate a person. Only sending the next command after the last one has completed. Possibly even after the output is processed as well.

Tracking console state

---

src/main/java/org/jboss/aesh/console/ProcessManager.java

Added a background stack that will auto-start background processes when the current process ends. Only does so if requested though.
Possible extension, doing this automatically somehow? Not sure how that would work though.

Extended background/foreground process functionality.

---

src/main/java/org/jboss/aesh/console/AeshProcess.java
src/main/java/org/jboss/aesh/console/command/CommandResult.java

An enumeration should never change it state (as it was done with setResultValue).

CommandResult should not be an enum

---

src/main/java/org/jboss/aesh/console/AeshConsoleCallback.java
src/main/java/org/jboss/aesh/console/AeshProcess.java
src/main/java/org/jboss/aesh/console/Console.java
src/main/java/org/jboss/aesh/console/ConsoleCallback.java
src/main/java/org/jboss/aesh/console/ProcessManager.java
src/main/java/org/jboss/aesh/console/command/CmdOperation.java
src/main/java/org/jboss/aesh/console/command/invocation/AeshCommandInvocation.java
src/main/java/org/jboss/aesh/console/command/invocation/CommandInvocation.java
src/main/java/org/jboss/aesh/console/keymap/BindingReader.java
src/main/java/org/jboss/aesh/console/keymap/KeyMap.java
src/main/java/org/jboss/aesh/terminal/Key.java
src/main/java/org/jboss/aesh/terminal/ShellWrapper.java
src/main/java/org/jboss/aesh/terminal/TestTerminal.java
src/main/java/org/jboss/aesh/terminal/utils/NonBlockingReader.java
src/test/java/org/jboss/aesh/console/aesh/AeshCommandInvocationServiceTest.java
src/test/java/org/jboss/aesh/console/aesh/AeshConsoleParsingTest.java
src/test/java/org/jboss/aesh/console/keymap/BindingReaderTest.java
src/test/java/org/jboss/aesh/console/keymap/KeyMapTest.java

There’s currently no real modification to the API, so that commands can’t leverage the new key map bindings yet.

Use KeyMap and binding reader to fix the AeshConsoleParsingTest

---

README.asciidoc

The snippet present at the README file won't work with the latest versions.

Update the snippet example to be compatible with latest versions

---

src/main/java/org/jboss/aesh/cl/Arguments.java
src/main/java/org/jboss/aesh/cl/parser/AeshCommandLineCompletionParser.java
src/main/java/org/jboss/aesh/cl/parser/ParserGenerator.java
src/main/java/org/jboss/aesh/console/AeshConsole.java
src/main/java/org/jboss/aesh/console/AeshConsoleImpl.java

This is a wildly CLI requirement.

Expose callback from console. Activator for argument

---

src/main/java/org/jboss/aesh/console/alias/AliasManager.java

https://issues.jboss.org/browse/AESH-369

[AESH-369] Show a message if alias name does not match aliasPattern.

---

src/main/java/org/jboss/aesh/console/AeshConsoleImpl.java
src/main/java/org/jboss/aesh/console/command/registry/CommandRegistry.java
src/main/java/org/jboss/aesh/console/command/registry/MutableCommandRegistry.java
src/test/java/org/jboss/aesh/console/aesh/AeshCommandRegistryTest.java

Fix for AESH-380

---

src/main/java/org/jboss/aesh/cl/completer/CompleterData.java
src/main/java/org/jboss/aesh/cl/parser/AeshCommandLineCompletionParser.java

Handling of an offset of value 0.

Fix for AESH-392

---

src/main/java/org/jboss/aesh/console/AeshConsoleBuffer.java

https://issues.jboss.org/browse/AESH-402
https://issues.jboss.org/browse/JBEAP-5827
Upstream PR: https://github.com/aeshell/aesh/pull/232

[AESH-402] Wrong cursor position after deleting all characters in second line

---

src/main/java/org/jboss/aesh/console/command/map/MapProcessedCommandBuilder.java
src/test/java/org/jboss/aesh/console/map/MapCommandTest.java
src/test/java/org/jboss/aesh/console/map/MyMapCommand.java

Convey dynamic option values to newly created options. Added unit test.

Fix for AESH-416. Convey dynamic Option values.

---

src/main/java/org/jboss/aesh/parser/Parser.java

Fix for https://issues.jboss.org/browse/WFCORE-1868

handle double backslash

---

src/main/java/org/jboss/aesh/parser/Parser.java
src/test/java/org/jboss/aesh/parser/ParserTest.java

backport https://github.com/aeshell/aesh/pull/237 to 0.66.+ branch.

Parser.doesStringContainOpenQuote() should ignore a comment

---

src/main/java/Example.java
src/main/java/org/aesh/command/AeshCommandProcessor.java
src/main/java/org/aesh/command/AeshCommandProcessorBuilder.java
src/main/java/org/aesh/command/AeshCommandProcessorImpl.java
src/main/java/org/aesh/command/CommandOperator.java
src/main/java/org/aesh/command/Executable.java
src/main/java/org/aesh/command/Executor.java
src/main/java/org/aesh/console/command/invocation/AeshCommandInvocation.java
src/main/java/org/aesh/console/command/invocation/CommandInvocation.java
src/test/java/org/aesh/console/aesh/AeshCommandInvocationServiceTest.java
src/test/java/org/aesh/console/aesh/AeshScriptTest.java

This is the basis for an Aesh commands processor uncoupled from any terminal.
It can execute,complete or build a fully injected Command.
This should be used when implementing the Aesh console.

A command processor

---

src/main/java/org/aesh/parser/LineParser.java

I found the failure in the last test in org.aesh.parser.LineParserTest.testOperatorParsing() and fixed it.

fixed LineParser.parseLine()

---

src/main/java/org/aesh/parser/LineParser.java

Similar to brackets, parenthesis parsing with operators.

parenthesis should hide operators

---

src/test/java/org/aesh/console/aesh/AeshCommandCompletionTest.java

These 2 new test cases are failing.
First one, that is caused by invalid offset computation when a whitespace exists in the value to complete.
Second one, that is caused by the fact that the command is a child command. In such case, AeshCommandLineCompletionParser.injectValuesAndComplete line 59, a new line is parsed, this changes the selectedWord,  and the status. Notice that parseCurlyAndSquareBrackets is not passed so is false.

Added failing completion testcases

---

aesh/src/main/java/org/aesh/command/map/MapProcessedCommandBuilder.java
aesh/src/test/java/org/aesh/command/map/MapCommandTest.java

-Fixed problem.
- Added unit test to cover MapCommand completion and execution.

Fix for AESH-480, and AESH-481

---

aesh/src/main/java/org/aesh/command/settings/Settings.java
aesh/src/main/java/org/aesh/command/settings/SettingsBuilder.java
aesh/src/main/java/org/aesh/command/settings/SettingsImpl.java
aesh/src/main/java/org/aesh/readline/PagingSupport.java
aesh/src/main/java/org/aesh/readline/ReadlineConsole.java
aesh/src/main/java/org/aesh/readline/ShellImpl.java
examples/src/main/java/examples/Example.java

Paging/scroll/search support.
NB: relies on a fix (for Ctrl-C handling) that will come in aesh-readline 1.11

Fix for AESH-486, scroll/search paging

---

aesh/src/main/java/org/aesh/command/map/MapProcessedCommandBuilder.java

Do call for dynamic options when doing this check.

Follow-up on AESH-485, Map Command adjustment

---

aesh/src/main/java/org/aesh/command/impl/invocation/DefaultCommandInvocation.java

https://github.com/aeshell/aesh/issues/320

Use Console.readPassword() in DefaultShell when masking is requested

---

aesh/src/main/java/org/aesh/util/graal/GraalReflectionCommand.java
aesh/src/main/java/org/aesh/util/graal/GraalReflectionFileGenerator.java

https://github.com/aeshell/aesh/issues/324

Fix native generator shortcomings
